defaults:
  - _self_
  - hydra

log:
  should_overwrite: true
  save_dir: "your_dir/ELLA/scripts/demo/mini_demo/lightning_logs/run1"

data:
  data_path: "your_dir/ELLA/scripts/demo/mini_demo/prepared_data/training_data.jsonl"
  gene_idx: 0

kernel_params:
  - a0: 1.0
    b0: 2.71
  - a0: 1.26
    b0: 3.34
  - a0: 2.05
    b0: 5.19
  - a0: 6.99
    b0: 14.98
  - a0: 19.41
    b0: 28.62
  - a0: 28.5
    b0: 28.5
  - a0: 28.62
    b0: 19.41
  - a0: 14.98
    b0: 6.99
  - a0: 5.19
    b0: 2.05
  - a0: 3.34
    b0: 1.26
  - a0: 2.71
    b0: 1.0
  - a0: 1.0
    b0: 2.0
  - a0: 1.13
    b0: 2.19
  - a0: 1.38
    b0: 2.52
  - a0: 1.88
    b0: 3.06
  - a0: 2.73
    b0: 3.6
  - a0: 3.5
    b0: 3.5
  - a0: 3.6
    b0: 2.73
  - a0: 3.06
    b0: 1.88
  - a0: 2.52
    b0: 1.38
  - a0: 2.19
    b0: 1.31
  - a0: 2.0
    b0: 1.0

model:
  is_debug: true
  optimizer:
    lr: 1e-3
  n_bins: 20
  beta_init: 0.1
  sigma02_init: 0.01

trainer:
  max_epochs: 200
  enable_progress_bar: false

estimation:
  search_dir: "${log.save_dir}"
  log_dir_pattern: "gene_${data.gene_idx}_kernel_.*"
  output_path: "${log.save_dir}/gene_${data.gene_idx}_estimation_result.json"
  n_bins: 50
